#!/bin/bash
set -e
echo === CharlieApp v3 Deploy ===
echo 1. Pushing to GitHub...
git push origin main || git push origin master
echo 2. Building Docker image...
docker build -t charlie-app:latest .
echo 3. Stopping old container...
docker stop charlie-app 2>/dev/null || true
docker rm charlie-app 2>/dev/null || true
echo 4. Starting new container...
docker run -d --name charlie-app -p 4000:4000 --restart unless-stopped charlie-app:latest
echo 5. Health check...
sleep 2
curl -f http://localhost:4000/api/status && echo DEPLOY OK
